# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Add_view import Ui_DialogAddView
from Add_quote import Ui_DialogAddQuote


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(932, 632)
        MainWindow.setStyleSheet("QMainWindow{background-color: qlineargradient(spread:reflect, x1:0, y1:1, x2:0.895, y2:0.142045, stop:0 rgba(0, 0, 0, 255), stop:0.920398 rgba(21, 209, 255, 255));}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGridVisible(False)
        self.calendarWidget.setSelectionMode(QtWidgets.QCalendarWidget.SingleSelection)
        self.calendarWidget.setObjectName("calendarWidget")
        self.verticalLayout.addWidget(self.calendarWidget)
        spacerItem = QtWidgets.QSpacerItem(58, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.pbAddQuote = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Tekton Pro")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pbAddQuote.setFont(font)
        self.pbAddQuote.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pbAddQuote.setAutoFillBackground(False)
        self.pbAddQuote.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.999, fx:0.5, fy:0.5, stop:0 rgba(4, 169, 131, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.pbAddQuote.setAutoDefault(True)
        self.pbAddQuote.setDefault(False)
        self.pbAddQuote.setFlat(True)
        self.pbAddQuote.setObjectName("pbAddQuote")
        self.verticalLayout.addWidget(self.pbAddQuote)
        spacerItem2 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem2)
        self.pbAddImage = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Tekton Pro")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pbAddImage.setFont(font)
        self.pbAddImage.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pbAddImage.setAutoFillBackground(False)
        self.pbAddImage.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.999, fx:0.5, fy:0.5, stop:0 rgba(4, 169, 131, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.pbAddImage.setCheckable(False)
        self.pbAddImage.setAutoDefault(True)
        self.pbAddImage.setFlat(True)
        self.pbAddImage.setObjectName("pbAddImage")
        self.verticalLayout.addWidget(self.pbAddImage)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(907, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 932, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.calendarWidget.clicked.connect(self.calendarClicked)
        self.pbAddQuote.clicked.connect(self.addQuoteClicked)
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
    def addQuoteClicked(self):
        self.DialogAddQuote = QtWidgets.QDialog()
        self.uiAddQuote = Ui_DialogAddQuote()
        self.uiAddQuote.setupUi(self.DialogAddQuote)
        self.DialogAddQuote.show()
    def calendarClicked(self):
        self.DialogAddView = QtWidgets.QDialog()
        self.ui1 = Ui_DialogAddView()
        self.ui1.setupUi(self.DialogAddView)
        self.DialogAddView.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pbAddQuote.setText(_translate("MainWindow", "Add a Motivational Quote"))
        self.pbAddQuote.setShortcut(_translate("MainWindow", "Q"))
        self.pbAddImage.setText(_translate("MainWindow", "Add a Reference Image"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
